import PDFDocument from "pdfkit";
import prisma from "../config/prisma";

export const generatePDFReport =
  async (
    candidateId: string,
    userId: string
  ) => {
    const candidate =
      await prisma.candidate.findFirst({
        where: {
          id: candidateId,
          createdById: userId,
        },
        include: {
          verificationLogs: {
            orderBy: {
              verifiedAt: "desc",
            },
          },
        },
      });

    if (!candidate) {
      throw new Error(
        "Candidate not found"
      );
    }

    const doc = new PDFDocument({
      margin: 50,
    });

    const chunks: Buffer[] = [];

    doc.on("data", (chunk) =>
      chunks.push(chunk)
    );

    return new Promise<Buffer>(
      (resolve, reject) => {
        doc.on("end", () => {
          resolve(
            Buffer.concat(chunks)
          );
        });

        doc.on(
          "error",
          reject
        );

        // HEADER
        doc
          .fontSize(24)
          .text(
            "VeriSure Verification Report",
            {
              align: "center",
            }
          );

        doc.moveDown();

        doc
          .fontSize(12)
          .text(
            `Generated: ${new Date().toLocaleString()}`
          );

        doc.moveDown();

        // CANDIDATE DETAILS
        doc
          .fontSize(18)
          .text(
            "Candidate Information",
            {
              underline: true,
            }
          );

        doc.moveDown(0.5);

        doc.text(
          `Full Name: ${candidate.fullName}`
        );

        doc.text(
          `Email: ${candidate.email}`
        );

        doc.text(
          `Phone: ${candidate.phone}`
        );

        doc.text(
          `DOB: ${candidate.dob.toDateString()}`
        );

        doc.text(
          `Address: ${candidate.address}`
        );

        doc.text(
          `Aadhaar: XXXXXXXX${candidate.aadhaarNumber.slice(
            -4
          )}`
        );

        doc.text(
          `PAN: ${candidate.panNumber.slice(
            0,
            3
          )}XXXXX`
        );

        doc.moveDown();

        // STATUS
        doc
          .fontSize(18)
          .text(
            "Verification Summary",
            {
              underline: true,
            }
          );

        doc.moveDown(0.5);

        doc.text(
          `Overall Status: ${candidate.verificationStatus}`
        );

        doc.moveDown();

        // LOGS
        doc
          .fontSize(18)
          .text(
            "Verification Timeline",
            {
              underline: true,
            }
          );

        doc.moveDown(0.5);

        candidate.verificationLogs.forEach(
          (log, index) => {
            doc
              .fontSize(12)
              .text(
                `${index + 1}. ${
                  log.verificationType
                }`
              );

            doc.text(
              `Status: ${log.verificationStatus}`
            );

            doc.text(
              `Verified At: ${log.verifiedAt.toLocaleString()}`
            );

            doc.moveDown();
          }
        );

        // FOOTER
        doc.moveDown(2);

        doc
          .fontSize(10)
          .text(
            "This document is system generated by VeriSure.",
            {
              align: "center",
            }
          );

        doc.end();
      }
    );
  };